# /get
from enum import StrEnum

GET_SERVICE_NAME = "GET_SERVICE_NAME"
GET_MASTER_PASSWORD = "GET_MASTER_PASSWORD"


class AddConstraints(StrEnum):
    ADD_SERVICE_NAME = ("ADD_SERVICE_NAME",)
    ADD_USERNAME = ("ADD_USERNAME",)
    ADD_PASSWORD = ("ADD_PASSWORD",)
    ADD_MASTER_PASSWORD_CONFIRM = ("ADD_MASTER_PASSWORD_CONFIRM",)
