services:

  api:
    image: denissedoved/pas_manager:latest
    restart: unless-stopped
    env_file:
      - .env

    volumes:
      - ./data:/app/data

    ports:
      - "8000:8000"
  # tunel:
  #   image: cloudflare/cloudflared:latest
  #   restart: unless-stopped
  #   command: tunnel --no-autoupdate run --token ${APP__TUNNEL_TOKEN}
  #   env_file:
  #     - .env
