"""rename-fields

Revision ID: cb52c5a3a720
Revises: c085f009d3bf
Create Date: 2026-03-16 11:41:29.342736

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "cb52c5a3a720"
down_revision: Union[str, Sequence[str], None] = "c085f009d3bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("category_name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("icon", sa.String(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("category_name", name=op.f("uq_categories_category_name")),
    )

    # 2. ПЕРЕНОС ДАННЫХ из platforms в categories
    # platform_name -> category_name
    op.execute(
        """
        INSERT INTO categories (id, category_name, description, icon, "order")
        SELECT id, platform_name, description, icon, "order"
        FROM platforms
        """
    )

    # 3. Работаем с таблицей accounts
    # Сначала добавляем колонку как nullable=True, чтобы была возможность заполнить её данными
    op.add_column("accounts", sa.Column("category_id", sa.Text(), nullable=True))

    # ПЕРЕНОС ДАННЫХ внутри accounts (связи)
    op.execute("UPDATE accounts SET category_id = platform_id")

    # Теперь настраиваем ограничения (Constraints) через batch_op
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        # Делаем колонку обязательной после заполнения
        batch_op.alter_column("category_id", nullable=False)

        # Удаляем старый FK и создаем новый
        batch_op.drop_constraint("fk_accounts_platform_id_platforms", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_accounts_category_id_categories"),
            "categories",
            ["category_id"],
            ["id"],
        )
        # Удаляем старую колонку
        batch_op.drop_column("platform_id")

    # 4. Удаляем старую таблицу только в самом конце
    op.drop_table("platforms")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "platforms",
        sa.Column("id", sa.TEXT(), nullable=False),
        sa.Column("platform_name", sa.VARCHAR(), nullable=False),
        sa.Column("description", sa.VARCHAR(), nullable=True),
        sa.Column("icon", sa.VARCHAR(), server_default=sa.text("'?'"), nullable=True),
        sa.Column("order", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platforms")),
        sa.UniqueConstraint("platform_name", name=op.f("uq_platforms_platform_name")),
    )

    # 2. ПЕРЕНОС ДАННЫХ обратно в platforms
    op.execute(
        """
        INSERT INTO platforms (id, platform_name, description, icon, "order")
        SELECT id, category_name, description, icon, "order"
        FROM categories
        """
    )

    # 3. Возвращаем колонку platform_id в accounts
    op.add_column("accounts", sa.Column("platform_id", sa.Text(), nullable=True))
    op.execute("UPDATE accounts SET platform_id = category_id")

    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.alter_column("platform_id", nullable=False)
        batch_op.drop_constraint(batch_op.f("fk_accounts_category_id_categories"), type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_accounts_platform_id_platforms"),
            "platforms",
            ["platform_id"],
            ["id"],
        )
        batch_op.drop_column("category_id")

    # 4. Удаляем таблицу categories
    op.drop_table("categories")
    # ### end Alembic commands ###
