"""order

Revision ID: 913d86d84b32
Revises: ae9eab3bfbf3
Create Date: 2026-03-13 16:35:18.286880

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "913d86d84b32"
down_revision: Union[str, Sequence[str], None] = "ae9eab3bfbf3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("platforms", sa.Column("order", sa.Integer(), nullable=True))

    # 2. Заполняем данные (вне блока batch, чтобы колонка точно уже существовала)
    op.execute('UPDATE platforms SET "order" = 0')

    # 3. Делаем колонку обязательной
    # Используем batch_alter_table здесь, так как это изменение существующей колонки
    with op.batch_alter_table("platforms", schema=None) as batch_op:
        batch_op.alter_column('order',
                              existing_type=sa.Integer(),
                              nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("platforms", schema=None) as batch_op:
        batch_op.drop_column("order")

    # ### end Alembic commands ###
