"""init

Revision ID: 4c252112b4d4
Revises:
Create Date: 2026-03-03 07:54:14.362193

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4c252112b4d4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "platforms",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("platform_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platforms")),
        sa.UniqueConstraint(
            "platform_name", name=op.f("uq_platforms_platform_name")
        ),
    )
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("platform_id", sa.UUID(), nullable=False),
        sa.Column("user_name", sa.String(), nullable=False),
        sa.Column("encrypted_data", sa.String(), nullable=False),
        sa.Column("salt", sa.String(), nullable=False),
        sa.Column("nonce", sa.String(), nullable=False),
        sa.Column("tag", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["platform_id"],
            ["platforms.id"],
            name=op.f("fk_accounts_platform_id_platforms"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("accounts")
    op.drop_table("platforms")
    # ### end Alembic commands ###
