"""fix-account-platform-id-required

Revision ID: dcba73fec760
Revises: 2d292af3745b
Create Date: 2026-03-11 08:57:25.840435

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dcba73fec760"
down_revision: Union[str, Sequence[str], None] = "2d292af3745b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()

    other_id = bind.execute(sa.text(
        "SELECT id FROM platforms WHERE platform_name = 'Other'"
    )).scalar()

    if not other_id:
        raise Exception("Default platform 'Other' not found. Run previous migration first.")

    bind.execute(sa.text(
        "UPDATE accounts SET platform_id = :other_id WHERE platform_id IS NULL"
    ), {"other_id": other_id})

    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.alter_column(
            "platform_id", existing_type=sa.TEXT(), nullable=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.alter_column(
            "platform_id", existing_type=sa.TEXT(), nullable=True
        )

    # ### end Alembic commands ###
