"""edit-column-in-platforms-table

Revision ID: ae9eab3bfbf3
Revises: b82e918139c8
Create Date: 2026-03-11 16:59:27.930502

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ae9eab3bfbf3"
down_revision: Union[str, Sequence[str], None] = "b82e918139c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("platforms", schema=None) as batch_op:
        batch_op.alter_column(
            "icon",
            existing_type=sa.VARCHAR(),
            nullable=True,
            existing_server_default=sa.text("'🌐'"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("platforms", schema=None) as batch_op:
        batch_op.alter_column(
            "icon",
            existing_type=sa.VARCHAR(),
            nullable=False,
            existing_server_default=sa.text("'🌐'"),
        )

    # ### end Alembic commands ###
