"""order-account

Revision ID: ac215dab4ae6
Revises: 913d86d84b32
Create Date: 2026-03-15 08:39:27.337371

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ac215dab4ae6"
down_revision: Union[str, Sequence[str], None] = "913d86d84b32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("accounts", sa.Column("order", sa.Integer(), nullable=True))

    # 2. Заполняем данные (вне блока batch, чтобы колонка точно уже существовала)
    op.execute('UPDATE accounts SET "order" = 0')

    # 3. Делаем колонку обязательной
    # Используем batch_alter_table здесь, так как это изменение существующей колонки
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.alter_column('order',
                              existing_type=sa.Integer(),
                              nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.drop_column("order")

    # ### end Alembic commands ###
