"""create-default-platform

Revision ID: 2d292af3745b
Revises: 9d7ca29decf1
Create Date: 2026-03-11 08:52:05.353440

"""

import uuid
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d292af3745b"
down_revision: Union[str, Sequence[str], None] = "9d7ca29decf1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    result = bind.execute(
        sa.text("SELECT id FROM platforms WHERE platform_name = 'Other'")
    ).fetchone()

    if not result:
        # 2. Генерируем UUID так же, как это делает твоя модель
        new_id = str(uuid.uuid4())

        # 3. Вставляем платформу с явным указанием сгенерированного ID
        bind.execute(
            sa.text("""
                             INSERT INTO platforms (id, platform_name, description)
                             VALUES (:id, 'Other', 'Default platform')
                             """),
            {"id": new_id},
        )

        other_id = new_id
    else:
        other_id = result[0]
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
