"""create-resource-table

Revision ID: 3c0e23c7b099
Revises: cb52c5a3a720
Create Date: 2026-03-16 13:20:04.221724

"""

import uuid
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3c0e23c7b099"
down_revision: Union[str, Sequence[str], None] = "cb52c5a3a720"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resources",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("resource_name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("icon", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resources")),
        sa.UniqueConstraint("resource_name", name=op.f("uq_resources_resource_name")),
    )

    # 2. Вставляем дефолтную запись
    bind = op.get_bind()
    default_id = str(uuid.uuid4())
    bind.execute(
        sa.text("""
                         INSERT INTO resources (id, resource_name, description)
                         VALUES (:id, 'Без площадки', 'По умолчанию')
                         """),
        {"id": default_id},
    )

    # 3. Добавляем колонку resource_id (nullable=True пока)
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("resource_id", sa.Text(), nullable=True))
        batch_op.create_foreign_key(
            op.f("fk_accounts_resource_id_resources"),
            "resources",
            ["resource_id"],
            ["id"],
        )

    # 4. Заполняем существующие аккаунты дефолтной площадкой
    bind.execute(
        sa.text(
            "UPDATE accounts SET resource_id = :default_id WHERE resource_id IS NULL"
        ),
        {"default_id": default_id},
    )

    # 5. Делаем NOT NULL
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.alter_column("resource_id", existing_type=sa.TEXT(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.drop_constraint(
            op.f("fk_accounts_resource_id_resources"), type_="foreignkey"
        )
        batch_op.drop_column("resource_id")
    op.drop_table("resources")
    # ### end Alembic commands ###
