"""create-account-platform-table

Revision ID: 9d7ca29decf1
Revises: 2aef0b58ba5f
Create Date: 2026-03-11 08:51:36.509629

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9d7ca29decf1"
down_revision: Union[str, Sequence[str], None] = "2aef0b58ba5f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("master_password_hash", sa.String(), nullable=False),
        sa.Column("encrypted_master_password", sa.String(), nullable=True),
        sa.Column("bio_enc_data", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_settings")),
    )
    op.create_table(
        "platforms",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("platform_name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platforms")),
        sa.UniqueConstraint("platform_name", name=op.f("uq_platforms_platform_name")),
    )
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("platform_id", sa.Text(), nullable=True),
        sa.Column("user_name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("tags", sa.String(), nullable=True),
        sa.Column("encrypted_data", sa.String(), nullable=False),
        sa.Column("salt", sa.String(), nullable=False),
        sa.Column("nonce", sa.String(), nullable=False),
        sa.Column("tag", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["platform_id"],
            ["platforms.id"],
            name=op.f("fk_accounts_platform_id_platforms"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
    )
    op.execute("""
               INSERT INTO accounts (user_name, encrypted_data, salt, nonce, tag)
               SELECT user_name, encrypted_data, salt, nonce, tag
               FROM account
               """)
    op.drop_table("account")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("service_name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("user_name", sa.VARCHAR(), nullable=False),
        sa.Column("encrypted_data", sa.VARCHAR(), nullable=False),
        sa.Column("salt", sa.VARCHAR(), nullable=False),
        sa.Column("nonce", sa.VARCHAR(), nullable=False),
        sa.Column("tag", sa.VARCHAR(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account")),
        sa.UniqueConstraint("service_name", name=op.f("uq_account_service_name")),
    )
    op.drop_table("accounts")
    op.drop_table("platforms")
    op.drop_table("app_settings")
    # ### end Alembic commands ###
